KznDotNet 3 and 4
DotNetRu/Audit pull request #198
Opened 2020-09-27 15:57 UTC by eliseev-ev

2020-10-04 16:23 UTC, AnatolyKulakov requested changes

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/meetups/KznDotNet-4.xml
> +  <Name>Встреча KznDotNet №3</Name>
`№4`

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/speakers/Andrey-Schilling/index.xml
> +  <Id>Andrey-Schilling</Id>
Файлы с фотографией должны называться `avatar.jpg` и `avatar.small.jpg`

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/speakers/Andrey-Schilling/index.xml
> +  <Description>Архитектор в компании Ак Барс Цифровые Технологии. Занимается проектированием мобильного банка, архитектурным рефакторингом и миграцией на микросервисы. До этого занимался интеграцией
> десктоп разработке на.net

1. В TimePad есть неприятный баг (фича): он удаляет пробел перед точкой. Даже если это название фреймворка. При копировании от туда нужно внимательно следить за этим моментом и возвращать пробел обратно.

2. Все по-разному коверкают название фреймворка, но правильное написание только одно — .NET.

Поэтому должно быть что-то типа:

> десктоп разработке на .NET

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/speakers/Dmitry-Polomoshnov/index.xml
> +  <Id>Dmitry-Polomoshnov</Id>
Файлы с фотографией должны называться avatar.jpg и avatar.small.jpg

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/speakers/Dmitry-Polomoshnov/index.xml
> +  <Description>Ведущий backend разработчик Ак Барс Цифровые Технологии. Более 15 лет занимается разработкой. Начинал с разработки на C++. Имеет опыт создания собственного проекта на.NET, в том числе
> собственного проекта на.NET

Пробел

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/talks/Developing-Production-Ready-AspNetCore.xml
> +  <SlidesUrl>https://vk.com/doc-161778786_469646688</SlidesUrl>
Все слайды должны быть обязательно на https://speakerdeck.com/dotnetru

Если эти слайды там уже есть, то просто добавь ссылку. Если нет, то скачай с VK и залей в наш репозиторий.

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/talks/OAuth-OpenId-Enterprise.xml
> +  <SlidesUrl>https://vk.com/doc-161778786_469646631</SlidesUrl>
Все слайды должны быть обязательно на https://speakerdeck.com/dotnetru

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/talks/Practical-Aspects-Migrating-To-Microservices.xml
> +  <SlidesUrl>https://vk.com/doc-161778786_469646719</SlidesUrl>
Все слайды должны быть обязательно на https://speakerdeck.com/dotnetru

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/talks/OAuth-OpenId-Enterprise.xml
> +  <Title>Аутентификация OAuth / OpenID Connect в Enterprise и среда Open API</Title>
«OAuth / OpenID» должно писаться без пробелов

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/talks/Practical-Aspects-Migrating-To-Microservices.xml
> +  <Description>Хайп вокруг микросервисов не утихает уже который год и сегодня они стали мейнстримом. К чему нужно быть готовым сразу, а что отложить на потом, ступая на этот путь? Мы поговорим про пр
>о чем не всегда пишут

«о ч**ё**м»

2020-10-04 16:23 UTC, AnatolyKulakov commented on db/venues/Kzn-Bars-Talent-Center.xml
> +  <Address>ул.Галиаскара Камала, 4</Address>
Добавь город

2020-10-11 10:43 UTC, eliseev-ev commented on db/meetups/KznDotNet-4.xml
> +  <Name>Встреча KznDotNet №3</Name>
Done

2020-10-11 10:44 UTC, eliseev-ev commented on db/speakers/Andrey-Schilling/index.xml
> +  <Id>Andrey-Schilling</Id>
done

2020-10-11 10:47 UTC, eliseev-ev commented on db/speakers/Andrey-Schilling/index.xml
> +  <Description>Архитектор в компании Ак Барс Цифровые Технологии. Занимается проектированием мобильного банка, архитектурным рефакторингом и миграцией на микросервисы. До этого занимался интеграцией
Done

2020-10-11 10:48 UTC, eliseev-ev commented on db/speakers/Dmitry-Polomoshnov/index.xml
> +  <Description>Ведущий backend разработчик Ак Барс Цифровые Технологии. Более 15 лет занимается разработкой. Начинал с разработки на C++. Имеет опыт создания собственного проекта на.NET, в том числе
done

2020-10-11 10:49 UTC, eliseev-ev commented on db/speakers/Dmitry-Polomoshnov/index.xml
> +  <Id>Dmitry-Polomoshnov</Id>
done

2020-10-11 11:50 UTC, merged